# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

#on:
#  release:
#    types: [created]

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/geocoderService.war"
        replacesArtifacts: true
        allowUpdates: false
        makeLatest: true
        tag: "GeocoderService-run${{ github.run_number }}"
        name: "GeocoderService"
        token: ${{ secrets.GITHUB_TOKEN }}

